"""
CWE / OWASP Top 10 classification lookup, keyed by vuln_class.

Deliberately NOT generated by the LLM. A local 8B model asked to recall
exact CWE numbers from memory risks hallucinating a plausible-looking but
wrong ID — unacceptable in a security report. Since this mapping is
static, well-established, and small, it's supplied by code and attached
to every triage verdict, while the LLM contributes what it's actually
good at: reasoning about the specific evidence, exploitability, and
remediation for this finding.
"""

from __future__ import annotations

CWE_OWASP_MAP: dict[str, dict[str, str]] = {
    "sqli": {
        "cwe_id": "CWE-89",
        "cwe_name": "Improper Neutralization of Special Elements used in an SQL Command ('SQL Injection')",
        "owasp_category": "A03:2021",
        "owasp_name": "Injection",
    },
    "xss": {
        "cwe_id": "CWE-79",
        "cwe_name": "Improper Neutralization of Input During Web Page Generation ('Cross-site Scripting')",
        "owasp_category": "A03:2021",
        "owasp_name": "Injection",
    },
    "cmdi": {
        "cwe_id": "CWE-78",
        "cwe_name": "Improper Neutralization of Special Elements used in an OS Command ('OS Command Injection')",
        "owasp_category": "A03:2021",
        "owasp_name": "Injection",
    },
    "path_traversal": {
        "cwe_id": "CWE-22",
        "cwe_name": "Improper Limitation of a Pathname to a Restricted Directory ('Path Traversal')",
        "owasp_category": "A01:2021",
        "owasp_name": "Broken Access Control",
    },
}


def get_standard_reference(vuln_class: str) -> str:
    """Returns a citation string like 'CWE-89 (OWASP A03:2021 - Injection)', or a fallback if the class is unmapped."""
    entry = CWE_OWASP_MAP.get(vuln_class)
    if entry is None:
        return "No standard classification mapped for this vulnerability class"
    return f"{entry['cwe_id']} (OWASP {entry['owasp_category']} - {entry['owasp_name']})"
